fix(test): Fix test about nvme mount for LocalStorageManagerTest (#2416)
### What changes were proposed in this pull request?

When I run the unit tests on the `/dev/nvme0n1p6` filesystem, Linux incorrectly assumes that this in a HDD. It tries to read info from `/sys/block/nvme0n1p/queue/rotational` but it should read info from `/sys/block/nvme0n1/queue/rotational`.

The method `getDeviceName` correctly removes the numbers at the end from `sda1` to create a device name `sda` but it does not handle nvme devices correctly, mount point  `nvme0n1p6` should return `nvme0n1` as device name, we need to remove the `p6` part. 

### Why are the changes needed?

```
[INFO] Running org.apache.uniffle.server.storage.LocalStorageManagerTest                                                 
[ERROR] Tests run: 7, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.879 s <<< FAILURE! - in org.apache.uniffle.server.storage.LocalStorageManagerTest
[ERROR] testGetLocalStorageInfo  Time elapsed: 0.091 s  <<< FAILURE!                                                     
org.opentest4j.AssertionFailedError: expected: <SSD> but was: <HDD>                 
        at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)                                             
        at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)                            
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)                               
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)                   
        at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1141) 
        at org.apache.uniffle.server.storage.LocalStorageManagerTest.testGetLocalStorageInfo(LocalStorageManagerTest.java:334)	
```

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
UT